name: shalat_essential
description: "A mobile prayer time app that automatically displays daily prayer schedules based on the user's location, complete with adhan notifications, Qibla compass, and a personal prayer tracking feature. Designed with a modern, lightweight interface and works offline."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  adhan_dart: ^1.1.2
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  timezone: ^0.10.1
  lat_lng_to_timezone: ^0.2.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.4
  launcher_name: ^1.0.2
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  page_transition: ^2.2.1
  cloud_firestore: ^6.0.0
  flutter_local_notifications: ^19.4.1
  shared_preferences: ^2.5.3
  flutter_compass: ^0.8.1
  home_widget: ^0.8.0
  receive_intent: ^0.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/compass.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

launcher_name:
  default: "Muslim Essential"


