// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'prayer_data.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5773730938993993981),
    name: 'PrayerData',
    lastPropertyId: const obx_int.IdUid(7, 6322474454303307640),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6148757172956881348),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 338590848365617383),
        name: 'date',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2006736924553821778),
        name: 'fajr',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 7360556543443327964),
        name: 'dhuhr',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 2262257206876941303),
        name: 'asr',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(6, 8402480542068871028),
        name: 'maghrib',
        type: 10,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(7, 6322474454303307640),
        name: 'isha',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    entities: _entities,
    lastEntityId: const obx_int.IdUid(1, 5773730938993993981),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    PrayerData: obx_int.EntityDefinition<PrayerData>(
      model: _entities[0],
      toOneRelations: (PrayerData object) => [],
      toManyRelations: (PrayerData object) => {},
      getId: (PrayerData object) => object.id,
      setId: (PrayerData object, int id) {
        object.id = id;
      },
      objectToFB: (PrayerData object, fb.Builder fbb) {
        final dateOffset = fbb.writeString(object.date);
        fbb.startTable(8);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, dateOffset);
        fbb.addInt64(2, object.fajr.millisecondsSinceEpoch);
        fbb.addInt64(3, object.dhuhr.millisecondsSinceEpoch);
        fbb.addInt64(4, object.asr.millisecondsSinceEpoch);
        fbb.addInt64(5, object.maghrib.millisecondsSinceEpoch);
        fbb.addInt64(6, object.isha.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final dateParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final fajrParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
        );
        final dhuhrParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
        );
        final asrParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
        );
        final maghribParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0),
        );
        final ishaParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0),
        );
        final object = PrayerData(
          id: idParam,
          date: dateParam,
          fajr: fajrParam,
          dhuhr: dhuhrParam,
          asr: asrParam,
          maghrib: maghribParam,
          isha: ishaParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [PrayerData] entity fields to define ObjectBox queries.
class PrayerData_ {
  /// See [PrayerData.id].
  static final id = obx.QueryIntegerProperty<PrayerData>(
    _entities[0].properties[0],
  );

  /// See [PrayerData.date].
  static final date = obx.QueryStringProperty<PrayerData>(
    _entities[0].properties[1],
  );

  /// See [PrayerData.fajr].
  static final fajr = obx.QueryDateProperty<PrayerData>(
    _entities[0].properties[2],
  );

  /// See [PrayerData.dhuhr].
  static final dhuhr = obx.QueryDateProperty<PrayerData>(
    _entities[0].properties[3],
  );

  /// See [PrayerData.asr].
  static final asr = obx.QueryDateProperty<PrayerData>(
    _entities[0].properties[4],
  );

  /// See [PrayerData.maghrib].
  static final maghrib = obx.QueryDateProperty<PrayerData>(
    _entities[0].properties[5],
  );

  /// See [PrayerData.isha].
  static final isha = obx.QueryDateProperty<PrayerData>(
    _entities[0].properties[6],
  );
}
